model: model1  # Name of model

trainer:
  log_path: logs/  # Path to save logs
  verbose: true  # Print logs on console
  save_freq: 10  # Save model every save_freq epochs. If 0, only the best model is saved

train:
  dataset: cifar10_train  # Dataset to use for training
  epochs: 20  # Number of training epochs
  num_workers: 4  # Number of workers for data loading
  batch_size: 32  # Training batch size
  train_val_split: 0.8  # Train/val split
  optimizer: sgd  # Optimizer
  loss: cross_entropy  # Loss function
  metrics: [accuracy]  # Metrics to evaluate
  scheduler: None  # Learning rate scheduler
  stop_condition: None  # Condition to stop training  

test:
  dataset: cifar10_test  # Dataset to use for testing
  checkpoint_path: logs/checkpoints/best_checkpoints.pth  # Path to checkpoint to load
  num_workers: 4  # Number of workers for data loading
  batch_size: 32  # Test batch size
  loss: cross_entropy  # Loss function
  metrics: [accuracy]  # Metrics to evaluate
