# Dataset
dataset:
  path: data/dataset1/

# Model
model:
  name: model1

# Training
training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam
  loss: cross_entropy
  metrics: [accuracy]
  stop_condition: val_loss
  model_checkpoint:
    save_freq: 10
    save_best_only: true

# Testing
testing:
  batch_size: 32
  metrics: [accuracy]

# Logging
logging:
  path: logs/
  level: info
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
